minimal_mistakes_skin    : "mint" # 태마 색 설정 "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "ko-KR"
title                    : "Web Development Blog" # Meta 태그에 들어가는 영역 , masthead_title등이 없으면 기본값으로 나온다.
title_separator          : "&#124;" # 타이틀 사이 구분자 <title>Welcome to Juntaekim Blog | Minimal Mistakes</title> 해당 형식으로 들어갑니다.
subtitle                 : "Version 1.000220120" # 타이틀 아래에 나올 작은 글씨
name                     : "김준태" # 맨 하단 이름 찍히는 영역
description              : "Front end , Sever , Laravel 등 다양한 개발을 공부하는 블로그" # Meta 태그에 들어가는 영역
url                      : #"https://developerJTkim.github.io/" # GitBlog 호스트 주소
baseurl                  : # subPath https://developerJTkim.github.io라고 하고 싶을 시 "/blog" 라고 적는다.
repository               : "developerJTkim/developerJTkim.github.com" # GitHub username/repo-name
teaser                   : # "/assets/images/senior-couple-4723737_640.jpg" # 홈페이지 기본 티져 이미지
logo                     : # 타이틀 옆에 작게 들어갈 이미지.
masthead_title           : "꾸준히 기록하고 성장하는 개발자 Blog" # 홈페이지 최 상탄에 들어갈 타이틀
breadcrumbs              : true # 브래드크럼 사용 여부 true, false (default) , _data/ui-text.yml에 다국어 지원 가능합니다.
words_per_minute         : 200 # 해당 포스트 읽는데 걸리는 시간을 계산하기 위해 대락 분당 읽는 수가 몇글자가 될지 적는 공간.

# Site Author
author:
  name             : "김준태"
  avatar           : "/assets/images/jtkim.jfif" # 프로필 이미지
  bio              : "안녕하세요. 개발자 김준태 입니다."
  location         : "Republic of Korea"
  email            : "juntaezz1@gmail.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:juntaezz1@gmail.com
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://developerJTkim.github.io"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://www.facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/developerJTkim"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/juntaezz2"

# Site Footer
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:juntaezz1@gmail.com
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://www.facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/developerJTkim"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/juntaezz2"

# Defaults Post들에 적용될 기본 설정들
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Outputting
paginate: 15                                    # Defaults : 5
paginate_path: /page:num/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  # - jemoji
  - jekyll-include-cache
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links